### ISSUE TITLE
Issue about ```n_epoch_pi != n_epoch_pi``` in ppo.py

### ISSUE THREAD

**Issue by hejujie** [openai/phasic-policy-gradient#1]
[https://github.com/openai/phasic-policy-gradient/blob/master/phasic_policy_gradient/ppo.py#L224](url)
When reading code for the Policy Phase in ppo.py, the equation ```n_epoch_pi != n_epoch_pi``` makes me confuse.

If n_epoch_pi is not specified, this equation will be false, the value network and policy network will train together.
If n_epoch_pi is specified, it will also be false, the value network and policy network will also train together. 

Whether this equation is typo of ```n_epoch_vf != n_epoch_pi```?  
So when n_epoch_pi is not specified or n_epoch_pi != n_epoch_vf, the optimization will perform separately for the policy network and the value network. 
and https://github.com/openai/phasic-policy-gradient/blob/master/phasic_policy_gradient/ppo.py#L230 also be ```nepoch=n_epoch_vf``` for udpate value network?

**Comment by wkwan** [comment]
To add to this, even if @hejujie is correct, if this code were to train the value network and the policy network separately, it would still be optimizing on the same model. Wouldn't it make more sense to be saving two separate models? Otherwise, what's the advantage of training the value and policy separately?

**Comment by christopher-hesse** [comment]
@kcobbe

**Comment by kcobbe** [comment]
Yes, you're absolutely right -- this is a bug. Thanks for the info. I just pushed a fix.
